### ISSUE TITLE
Starting neo4j on Jupyter notebook (Windows)

### ISSUE THREAD

**Issue by ery010** [covid-19-net/covid-19-community#12]
In 3-ExampleQueries, the code for starting Neo4J from the Jupyter Notebook does not appear to work on my machine (Windows 10 PC). However, it seems like this can be resolved by adjusting some of the code.

What worked for me:
Instead of `!"$NEO4J_HOME"/bin/neo4j start`, switch the direction of the slashes to `!"$NEO4J_HOME"\bin\neo4j start`. 
The command `!"$NEO4J_HOME"\bin\neo4j start` may also result in an error "Service neo4j not found". This can be resolved by running `!"$NEO4J_HOME"\bin\neo4j uninstall-service`, and then `!"$NEO4J_HOME"\bin\neo4j install-service`. 

I am unsure if the issues I encountered are Windows specific or only to my own machine, but the above are the changes that allow me to use the notebook as intended.

**Comment by pwrose** [comment]
The COVID KG has become too large to construct on laptop or desktop. I'm closing this ticket.
