### ISSUE TITLE
Automate batch upload of node and relationship files

### ISSUE THREAD

**Issue by pwrose** [covid-19-net/covid-19-community#2]
Batch upload all node and relationship file in the /data directory:

See: https://github.com/covid-19-net/covid-19-community/blob/master/notebooks/2-CreateGraph.ipynb

**Comment by GillesBodart** [comment]
What do you wanna change from your jupyter notebook ?

**Comment by pwrose** [comment]
Rather than specifying the specific list of node and relationship files,
upload all the files in the data and reference_data directories. That way
we don't need to update the CreateGraph notebook when we add new files.

**Comment by GillesBodart** [comment]
I'll try to see if I can do something for that than

**Comment by pwrose** [comment]
Great, send a pull request when you have something.

**Comment by GillesBodart** [comment]
Here you go #4

**Comment by GillesBodart** [comment]
I've made some changes #7

**Comment by pwrose** [comment]
We've done a complete refactoring, so this issue doesn't apply anymore.
