### ISSUE TITLE
I can contribute to model Events (Covid Test, Information, Death) related to a Person

### ISSUE THREAD

**Issue by AdamantasMario** [covid-19-net/covid-19-community#28]
I can contribute to model Events (Covid Test, Information, Death) related to a Person.

Related to that I would like to colaborate to model relationships between  people and model the Cell Phone tracking and location.

Furthermore, I could contribute to model tracking of people location based on the use of credit cards in shops, ATMs, etc.

Thanks in advance for your consideration.

Mario Íñiguez

**Comment by pwrose** [comment]
@AdamantasMario we are currently working on adding case data from Johns Hopkins and from the CovidDataScraper project.

What data source did you have in mind for cell phone tracking, credit cards, ATMs, etc?

**Comment by pwrose** [comment]
Please reopen if you find any publically available data about cell phone tracking, credit cards, ATMs, etc.
