### ISSUE TITLE
re. Question on communication between Covid-19-related projects using Neo4j

### ISSUE THREAD

**Issue by ibalaur** [covid-19-net/covid-19-community#318]
Dear All,

I am writing you now to briefly introduce the COVID-19 Disease Map community project: https://covid.pages.uni.lu/, which includes manual-curated, domain-expert-approved information on COVID-19 disease mechanisms. We also have a Neo4j-dedicated component and we are interested in creating a communication between the COVID-19-Net and the COVID-19 Disease Map project. I am looking forward to learning your opinion on this.

Thank you for your time.

Best regards,
Irina Balaur

**Comment by pwrose** [comment]
@ibalaur should we schedule a meeting to share some info about our projects and see if there are collaboration opportunities? You can email me at pwrose@ucsd.edu. -Peter

**Comment by pwrose** [comment]
We'll keep in touch by email.
