### ISSUE TITLE
Not able to generate the dataset completely

### ISSUE THREAD

**Issue by jaisyking** [covid-19-net/covid-19-community#320]
In readme file, for the data preparation step, files inside dataprep has to be run numerically or alphanumerically? When I tried to run numerically i.e, 00b-NCBITaxonomy.ipynb  an error occured. Also, when I ran alphanumerically 5 files reported error as they were not able to find the required files in the cache folder.

**Comment by pwrose** [comment]
@jaisyking The data preparation steps need to be updated. Some files need to be downloaded into the cache directory before running the notebooks.

To download the NCBI taxonomy files into the cache directory, please run this [script](https://github.com/covid-19-net/covid-19-community/blob/master/scripts/download.sh)

**Comment by jaisyking** [comment]
Hi, I have downloaded the NCBI taxonomy now. But I am not able to download CNCB strain data. I am attaching the screenshots of the error I am getting.

![Screenshot from 2021-04-09 15-13-10](https://user-images.githubusercontent.com/56273206/114163490-dfb76d00-9947-11eb-8ee6-75b33f25da2e.png)

**Comment by pwrose** [comment]
The CNCB ftp site is back. The downloads should work again.
