### ISSUE TITLE
Files in Geolink are obsolete

### ISSUE THREAD

**Issue by rwforest** [covid-19-net/covid-19-community#363]
It looks like these have been marked as obsolete, is 10-GeoLink still needed?

df4 = pd.read_csv(NEO4J_IMPORT / '02b-CDSCases.csv', dtype='str', usecols=['origLocation'])
df5 = pd.read_csv(NEO4J_IMPORT / '02d-GOBMXCasesAdmin1.csv', dtype='str', usecols=['origLocation'])
df6 = pd.read_csv(NEO4J_IMPORT / '02d-GOBMXCasesAdmin2.csv', dtype='str', usecols=['origLocation'])

**Comment by pwrose** [comment]
Yes, GeoLink is still needed to link JHU cases and strain (variant) data to geolocations.

**Comment by rwforest** [comment]
But the csv are no longer available, how do I get those?
