### ISSUE TITLE
How to run these notebooks

### ISSUE THREAD

**Issue by shainaraza** [covid-19-net/covid-19-community#380]
I run the cypher queries with neo4j however, I am confused as to how to use notebooks, is my assumption correct that first we need to have the graphs ready by running all cypher queries and then connect the notebooks with the neo4j source to run them?

**Comment by pwrose** [comment]
@shainaraza, sorry, I missed your message.

To run the notebooks, click on the "Launch Binder" button on the GitHub page. This will launch Jupyter Lab in your web browser (it make take a few minutes to launch). Once Jupyter Lab is up, navigate to any of the notebooks and run them.

The COVID-19-Net database runs on a server. The notebooks connect to the server to run the queries.

Please let me know if you have any trouble running the notebooks.

**Comment by pwrose** [comment]
Please reopen issue if you have more questions.
